# -*- coding: utf-8 -*-
"""Language translation tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17CV6L6HSSNw6WDlLa8CKaS3Qj6PYc-pH
"""

!pip install googletrans==3.1.0a0

import googletrans
from googletrans import Translator, LANGUAGES
import ipywidgets as widgets
from IPython.display import display

# Initialize the translator
translator = Translator()

# Create the widgets for input text, output text, and language selection
input_text = widgets.Textarea(
    value='',
    placeholder='Enter text to translate...',
    description='Input:',
    disabled=False,
    layout=widgets.Layout(width='70%')
)

output_text = widgets.Textarea(
    value='',
    placeholder='Translated text will appear here...',
    description='Output:',
    disabled=True,
    layout=widgets.Layout(width='70%', height='200px')
)

language_dropdown = widgets.Dropdown(
    options=[(language, code) for code, language in LANGUAGES.items()],
    value='en',  # Default to English
    description='Language:',
    disabled=False
)

translate_button = widgets.Button(
    description="Translate",
    button_style='success',
    tooltip="Click to translate",
    icon='check'
)

# Translate function
def on_translate_button_clicked(b):
    text = input_text.value
    dest_lang = language_dropdown.value
    if text:
        translated = translator.translate(text, dest=dest_lang)
        output_text.value = translated.text
    else:
        output_text.value = "Please enter some text to translate."

# Link the translate function to the button
translate_button.on_click(on_translate_button_clicked)

# Display all widgets
display(input_text, language_dropdown, translate_button, output_text)

